# Generated by Django 6.0.3 on 2026-03-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('x', models.FloatField(default=0, verbose_name='Позиция X на карте')),
                ('y', models.FloatField(default=0, verbose_name='Позиция Y на карте')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.ImageField(upload_to='device_icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Типы устройств',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер этажа')),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='floors/', verbose_name='Карта этажа')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('svg_id', models.CharField(max_length=50, verbose_name='ID на SVG-карте')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Модель')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('responsible_person', models.CharField(blank=True, max_length=200, verbose_name='Ответственное лицо')),
                ('contact_info', models.CharField(blank=True, max_length=300, verbose_name='Контактные данные')),
                ('x', models.FloatField(default=100, verbose_name='Позиция X')),
                ('y', models.FloatField(default=100, verbose_name='Позиция Y')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mappy.devicetype', verbose_name='Тип устройства')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='mappy.floor', verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='mappy.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Офис',
                'verbose_name_plural': 'Офисы',
            },
        ),
        migrations.AddField(
            model_name='floor',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='mappy.office', verbose_name='Офис'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='mappy.region', verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('line', 'Линия'), ('arrow', 'Стрелка')], default='line', max_length=10, verbose_name='Тип линии')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Подпись')),
                ('device_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='mappy.device', verbose_name='Устройство A')),
                ('device_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='mappy.device', verbose_name='Устройство B')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
                'unique_together': {('device_a', 'device_b')},
            },
        ),
    ]
