# Generated by Django 6.0.3 on 2026-03-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='waypoints',
            field=models.JSONField(blank=True, default=list, verbose_name='Точки маршрута'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='builtin_icon',
            field=models.CharField(blank=True, max_length=100, verbose_name='Встроенная иконка'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='line_type',
            field=models.CharField(choices=[('line', 'Линия'), ('arrow', 'Стрелка')], default='arrow', max_length=10, verbose_name='Тип линии'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='device_icons/', verbose_name='Иконка'),
        ),
    ]
