# Generated by Django 6.0.3 on 2026-05-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappy', '0006_connection_line_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='icon_scale',
            field=models.FloatField(default=1.0, help_text='1.0 = стандартный размер, 0.5 = в два раза меньше, 2.0 = в два раза больше', verbose_name='Масштаб иконки'),
        ),
    ]
