# nginx.conf — конфигурация веб-сервера, выступающего фронтом перед gunicorn.

events {
    worker_connections 1024;
}

http {
    client_max_body_size 50M;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /dev/stdout;
    error_log /dev/stderr;

    resolver 10.89.0.1 valid=10s ipv6=off;

    server {
        listen 80;
        server_name _;

        location = /nginx-health {
            return 200 "OK";
        }

        location /static/ {
            alias /srv/static/;
        }

        location /internal-media/ {
            internal;
            alias /srv/media/;
        }

        location / {
            set $backend "http://web:8000";
            proxy_pass $backend;

            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}