# Generated by Django 6.0.3 on 2026-05-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_seed_snmp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monitoringhistory',
            new_name='monitoring__device__4d51c5_idx',
            old_name='monitoring_hist_idx',
        ),
        migrations.AlterField(
            model_name='devicemonitorconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devicemonitorconfig',
            name='params',
            field=models.JSONField(blank=True, default=dict, help_text='Переопределяют глобальные параметры протокола', verbose_name='Параметры устройства'),
        ),
        migrations.AlterField(
            model_name='globalmonitorsettings',
            name='auto_poll_enabled',
            field=models.BooleanField(default=True, help_text='Участвует ли этот протокол в периодическом сканировании', verbose_name='Автоматический опрос'),
        ),
        migrations.AlterField(
            model_name='globalmonitorsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='globalmonitorsettings',
            name='params',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-словарь параметров. Переопределяют default_params протокола.', verbose_name='Глобальные параметры'),
        ),
        migrations.AlterField(
            model_name='globalmonitorsettings',
            name='poll_interval',
            field=models.IntegerField(default=300, help_text='Интервал автоматического опроса для этого протокола', verbose_name='Интервал опроса (сек)'),
        ),
        migrations.AlterField(
            model_name='monitoringhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monitorprotocol',
            name='default_params',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-словарь значений по умолчанию: {"timeout": 2, ...}', verbose_name='Параметры по умолчанию'),
        ),
        migrations.AlterField(
            model_name='monitorprotocol',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Если выключен — протокол не предлагается при настройке', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='monitorprotocol',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monitorprotocol',
            name='param_schema',
            field=models.JSONField(blank=True, default=list, help_text='JSON-массив описаний полей: [{"key","label","type","default"}, ...]', verbose_name='Схема параметров'),
        ),
    ]
